config/routes.rb
Rails.application.routes.draw do
  resources :appointments

  devise_for :users
  resources :users do
    resources :appointments
  end
  get 'home/index'
  root 'home#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/appointment.rb
class Appointment < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  enum role: [:patient, :doctor, :admin]
  after_initialize :set_default_role, :if => :new_record?

  def set_default_role
    self.role ||= :patient
  end

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  def after_sign_out_path_for(current_user)
   new_user_session_path
  end

  config.to_prepare do
    Devise::SessionsController.layout "devise"
    Devise::RegistrationsController.layout "devise"
    Devise::ConfirmationsController.layout "devise"
    Devise::UnlocksController.layout "devise"
    Devise::PasswordsController.layout "devise"
  end
end

app/controllers/appointments_controller.rb
class AppointmentsController < ApplicationController
  before_action :authenticate_user!
  def index
    role = (current_user.role + "_id").to_sym if current_user.role
    if params[:user_id]
      @title = "My Appointments"
      @appointments = Appointment.where(role => current_user.id) || []
    else
      @title = "Open Appointments"
      @appointments = Appointment.where(role => nil) || []
    end
  end

  def show
    begin
      appointment = Appointment.find(params[:id])
      @key = ENV["TOKBOX_API_KEY"]
      @secret = ENV["TOKBOX_API_SECRET"]
      @session = appointment.session
      @token = appointment.token
    rescue
      @create_appointment = true
    end
  end

  def new
  end

  def create
    opentok = TokBox.new.opentok
    @session = opentok.create_session
    @token = @session.generate_token
    @appointment = Appointment.new(session: @session, token: @token)
    @appointment.save
    redirect_to appointments_path
  end

  def edit
  end

  def update
    appointment = Appointment.find(params[:id])
    if params[:type] == "patient"
      appointment.patient_id = current_user.id
    else
      appointment.doctor_id = current_user.id
    end
    appointment.save
    redirect_to appointments_path
  end

  def destroy
  end
end

app/controllers/home_controller.rb
require "opentok"
class HomeController < ApplicationController
  before_action :authenticate_user!
  def index
    begin
      appointment = Appointment.where(patient_id: current_user.id).or(Appointment.where(doctor_id: current_user.id)).first
      @key = ENV["TOKBOX_API_KEY"]
      @secret = ENV["TOKBOX_API_SECRET"]
      @session = appointment.session
      @token = appointment.token
    rescue
      @create_appointment = true
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/appointments_helper.rb
module AppointmentsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/appointments/create.html.erb
<h1>Appointments#create</h1>
<p>Find me in app/views/appointments/create.html.erb</p>

app/views/appointments/destroy.html.erb
<h1>Appointments#destroy</h1>
<p>Find me in app/views/appointments/destroy.html.erb</p>

app/views/appointments/edit.html.erb
<h1>Appointments#edit</h1>
<p>Find me in app/views/appointments/edit.html.erb</p>

app/views/appointments/index.html.erb
<h1><%= @title %></h1>

<%= link_to "Create New Appointment", appointments_path(), :method => :post %>
<br />
<% @appointments.each do |appointment| %>
  <h3><%= appointment.id %></h3>
  <% if appointment.patient_id.nil? && current_user.role == "patient" %>
    <%= link_to "Join as Patient", appointment_path(id: appointment.id, type: "patient"), :method => :put %>
  <% end %>
  <% if appointment.doctor_id.nil? && current_user.role == "doctor" %>
    <br />
    <%= link_to "Join as Doctor", appointment_path(id: appointment.id, type: "doctor"), :method => :put %>
  <% end %>
  <% if (appointment.doctor_id == current_user.id && current_user.role == "doctor") || (appointment.patient_id == current_user.id && current_user.role == "patient")%>
    <br />
    <%= link_to "Start Appointment", appointment_path(appointment) %>
  <% end %>
<% end %>

app/views/appointments/new.html.erb
<h1>Appointments#new</h1>
<p>Find me in app/views/appointments/new.html.erb</p>

app/views/appointments/show.html.erb
<div class="row">
  <div class="col s4"> </div>
  <div class="col s4">
    <h1>Appointments#show</h1>
    <%= link_to 'Sign Out', destroy_user_session_path(@current_user), :method => :delete %>
    <br />
    <%= link_to 'See Appointments', appointments_path %>
    <p>Find me in app/views/appointments/show.html.erb</p>
    <div id="videoSubscriber">
    </div>
    <br />
    <div id="videoPublisher">
    </div>

    <% if @create_appointment %>
      <div>
        <%= link_to "Create an Appointment", appointments_index_path() %>
      </div>
    <% else %>
      <script src="https://static.opentok.com/v2/js/opentok.js" charset="utf-8"></script>
      <script charset="utf-8">
      var apiKey = '<%= @key %>';
      var sessionId = '<%= @session %>';
      var token = '<%= @token %>';
      var options = {width: 400, height: 300, insertMode: 'append'};
      var session = OT.initSession(apiKey, sessionId)
      .on('streamCreated', function(event) {
      session.subscribe(event.stream, 'videoSubscriber', options);
      })
      .connect(token, function(error) {
      var publisher = OT.initPublisher('videoPublisher', options);
      session.publish(publisher);
      });
      </script>
    <% end %>
  </div>
  <div class="col s4"> </div>
</div>

app/views/appointments/update.html.erb
<h1>Appointments#update</h1>
<p>Find me in app/views/appointments/update.html.erb</p>

app/views/home/index.html.erb
<h1 class="center-align">Welcome to Telemedicine</h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Tokbox</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">

  </head>

  <body>
    <ul id="dropdown1" class="dropdown-content">
      <li><%= link_to "Home", root_path %></li>
      <li class="divider"></li>
      <li><%= link_to "Open Appointments", appointments_path() %></li>
      <li class="divider"></li>
      <li><%= link_to "My Appointments", user_appointments_path(current_user) %></li>
      <li class="divider"></li>
      <li><%= link_to "Edit Profile", edit_user_registration_path %></li>
    </ul>
    <nav>
      <div class="nav-wrapper">
        <a href="#" class="brand-logo">Logo</a>
        <ul id="nav-mobile" class="right hide-on-med-and-down">
          <li>Status: <%= current_user.role %></li>
          <li><a class="dropdown-button" href="#!" data-activates="dropdown1"><%= current_user.email %><i class="material-icons right">arrow_drop_down</i></a></li>
          <li>
          <%- if user_signed_in? %>
          <%= link_to 'Sign Out', destroy_user_session_path(), :method => :delete %><br />
          <%- else %>
          <%= link_to "Log in", new_session_path() %><br />
          <% end -%>
          </li>
        </ul>
      </div>
    </nav>
    <div class="container">
        <div class="col s2"> </div>
        <div class="col s8">
          <%= yield %>
        </div>
        <div class="col s2"> </div>

    </div>
  </body>
</html>

app/views/layouts/devise.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Tokbox</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="http://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">

  </head>

  <body>
    <%- if current_user %>
    <ul id="dropdown1" class="dropdown-content">
      <li><%= link_to "Home", root_path %></li>
      <li class="divider"></li>
      <li><%= link_to "Open Appointments", appointments_path() %></li>
      <li class="divider"></li>
      <li><%= link_to "My Appointments", user_appointments_path(current_user) %></li>
      <li class="divider"></li>
      <li><%= link_to "Edit Profile", edit_user_registration_path %></li>
    </ul>
    <%- end %>
    <nav>
      <div class="nav-wrapper">
        <a href="#" class="brand-logo">Logo</a>
        <ul id="nav-mobile" class="right hide-on-med-and-down">
          <li><%= "Status: #{current_user.role}" if current_user %></li>
          <%- if current_user %>
            <li><a class="dropdown-button" href="#!" data-activates="dropdown1"><%= current_user.email %><i class="material-icons right">arrow_drop_down</i></a></li>
          <%- end %>
        </ul>
      </div>
    </nav>
    <div class="row">
      <div class="col s4"> </div>
      <div class="col s4">
        <%= yield %>
      </div>
      <div class="col s4"> </div>
    </div>
  </body>
</html>